export const ROUTE_PATHS = {
  home: '/',
  safety360: '/safety-360',
  about: '/about',
  solutions: '/solutions',
  features: '/features',
  industries: '/industries',
  howItWorks: '/how-it-works',
  demo: '/demo',
  caseStudies: '/case-studies',
  resources: '/resources',
  team: '/team',
  faq: '/faq',
  contact: '/contact',
  privacy: '/privacy-policy',
} as const;
